package com.example.project.Airport;
import java.util.ArrayList;

public class Airport  {
    /** A list of the flights into and out of this airport
     *  Guaranteed not to be null and to contain only non-null entries
     */
    private ArrayList<Flight> allFlights;

    public Airport(ArrayList<Flight> flights) {
        allFlights = flights;
    }

    public ArrayList<Flight> getAllFlights() {
        return allFlights;
    }

    /** Returns the revenue generated by all flights at the airport,
     *  as described in part (a)
     */
    public double getTotalRevenue() {
        double TotalR=0.0;
        for(Flight f:allFlights){
            if(f.getCapacity()>f.getNumPassengers()){
                TotalR+=f.getPrice()*f.getNumPassengers();
            }else{
                TotalR+=f.getPrice()*f.getCapacity();
            }
        }
        return TotalR;
    }

    /** Updates the list of flights by removing certain flights and
     *  returns the total number of passengers whose flights were removed,
     *  as described in part (b)
     */
    public int updateFlights() {
        int passengers=0;
        for (int index = 0; index < allFlights.size(); index++) {
            if(allFlights.get(index).getCapacity()*.2>allFlights.get(index).getNumPassengers()){
                passengers+=allFlights.remove(index).getNumPassengers();
                index--;
            }
        }
        return passengers;
    }
}